[theme]
primaryColor = "#ff4b4b"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"
base = "dark"

[server]
maxUploadSize = 1000  # Set the limit in MB (e.g., 1000 for 1GB)